// flow-typed signature: 466ca66adfb8dba886c5fb0d385c31db
// flow-typed version: <<STUB>>/jstransformer-markdown-it_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jstransformer-markdown-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jstransformer-markdown-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jstransformer-markdown-it/index' {
  declare module.exports: $Exports<'jstransformer-markdown-it'>;
}
declare module 'jstransformer-markdown-it/index.js' {
  declare module.exports: $Exports<'jstransformer-markdown-it'>;
}
