// flow-typed signature: b9939bf6f69a1300f5c8db8f170b03aa
// flow-typed version: <<STUB>>/jstransformer-remarkable_v^1.1.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jstransformer-remarkable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jstransformer-remarkable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jstransformer-remarkable/index' {
  declare module.exports: $Exports<'jstransformer-remarkable'>;
}
declare module 'jstransformer-remarkable/index.js' {
  declare module.exports: $Exports<'jstransformer-remarkable'>;
}
