// flow-typed signature: 54cd3a9db9b1a045d97772cd82eaebad
// flow-typed version: <<STUB>>/jstransformer-supermarked_v^0.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jstransformer-supermarked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jstransformer-supermarked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jstransformer-supermarked/index' {
  declare module.exports: $Exports<'jstransformer-supermarked'>;
}
declare module 'jstransformer-supermarked/index.js' {
  declare module.exports: $Exports<'jstransformer-supermarked'>;
}
