// flow-typed signature: fe388fcbc15c807e2e853873a30d5715
// flow-typed version: <<STUB>>/normalize.css_v^4.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
